apiVersion: v1
kind: Pod
metadata:
  name: novostoic-modelgen
spec:
  nodeSelector:
    ncsa.role: "worker-gpu"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: In
            values:
            - "true"
  containers:
    - name: modelgen
      image: "moleculemaker/novostoic"
      command:
        - sleep
        - "3600"
      stdin: true 
      tty: true 
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
