ingress:
  ingressClassName: nginx

postgresql:
  enabled: true
#  global:
#    storageClass: hostpath
  auth:
    rootPassword: "postgres"
    password: "postgres"
    username: "postgres"
    database: "mmli"

minio:
  enabled: true
  ingress:
    ingressClassName: nginx
#  global:
#    storageClass: hostpath
  auth:
    rootUser: minioadmin
    rootPassword: minioadmin
