ingress:
  ingressClassName: nginx

config:
  existingSecret: mmli-backend-secrets
  external:
    chemscraper:
      # Change to local chemscraper service URL if deployed in local cluster
      apiBaseUrl: "https://chemscraper.backend.staging.mmli1.ncsa.illinois.edu"
      frontendBaseUrl: "http://localhost:4200"

controller:
  image: moleculemaker/mmli-backend:kubejob

  # Change to local chemscraper service URL if deployed in local cluster
  # TODO: fit this into new config structure
  chemscraper_url: "https://chemscraper.backend.staging.mmli1.ncsa.illinois.edu"
  novostoic_frontend_url: "http://localhost:4200"
  somn_frontend_url: "http://localhost:4200"
  chemscraper_frontend_url: "http://localhost:4200"
  clean_frontend_url: "http://localhost:4200"
  molli_frontend_url: "http://localhost:4200"
  aceretro_frontend_url: "http://localhost:4200"
  reactionminer_frontend_url: "http://localhost:4200"
  openenzymedb_frontend_url: "http://localhost:4200"

postgresql:
  enabled: true
  autoschema: true
#  global:
#    storageClass: hostpath
  auth:
    password: "postgres"
    postgresPassword: "postgres"
    username: "postgres"
    database: "mmli"

minio:
  enabled: true
  apiIngress:
    ingressClassName: nginx
  ingress:
    ingressClassName: nginx
#  global:
#    storageClass: hostpath
  auth:
    rootUser: minioadmin
    rootPassword: minioadmin
