ingress:
  hostname: mmli.fastapi.localhost
  tls: false
  annotations: {}

controller:
  image: moleculemaker/mmli-backend

# https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values
postgresql:
  enabled: true
  hostname: ""
  auth:
    # Use an existing secret - this overrides username, password, and rootPassword
    # existingSecret: ""

    # Local development only - hardcode credentials here for simplicity
    # rootPassword: ""
    # password: ""

    # Set the name of your postgresql user
    username: "postgres"

    # Set the name of your postgresql database
    database: "mmli"

# https://artifacthub.io/packages/helm/bitnami/minio?modal=values
minio:
  enabled: true
  apiIngress:
    enabled: true
    tls: false
    hostname: minioapi.mmli.fastapi.localhost
    annotations: {}
  ingress:
    enabled: true
    tls: false
    hostname: minio.mmli.fastapi.localhost 
    annotations: {}
  auth:
    # Use an existing secret - this overrides username, password, and rootPassword
    # existingSecret: ""

    # Local development only - hardcode credentials here for simplicity
    # rootUser: "admin"
    # rootPassword: ""
