ingress:
  hostname: mmli.fastapi.localhost
  tls: false
  annotations: {}

controller:
  image: moleculemaker/mmli-backend:pr-1

# https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values
postgresql:
  enabled: true
  auth:
    # Use an existing secret - this overrides username, password, and rootPassword
    # existingSecret: ""

    # Local development only - hardcode credentials here for simplicity
    # rootPassword: ""
    # password: ""

    # Set the name of your postgresql user
    username: "postgres"

    # Set the name of your postgresql database
    database: "mmli"

# https://artifacthub.io/packages/helm/bitnami/minio?modal=values
minio:
  enabled: true
  auth:
    # Use an existing secret - this overrides username, password, and rootPassword
    # existingSecret: ""

    # Local development only - hardcode credentials here for simplicity
    # rootUser: "admin"
    # rootPassword: ""
