controller:
  image: moleculemaker/mmli-backend:main

ingress:
  hostname: mmli.fastapi.mmli1.ncsa.illinois.edu
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-cors-header@kubernetescrd

config:
  chemscraper_url: "http://chemscraper-services.alphasynthesis.svc.cluster.local:8000"
  chemscraper_frontend_url: "https://chemscraper.platform.moleculemaker.org"

postgresql:
  enabled: true
  hostname: mmli-backend-postgresql.alphasynthesis.svc.cluster.local
  global:
    storageClass: csi-cinder-sc-retain
  auth:
    existingSecret: "mmli-backend-postgresql"
    username: "postgres"
    database: "mmli"

minio:
  enabled: true
  apiIngress:
    tls: true
    hostname: minioapi.mmli.fastapi.mmli1.ncsa.illinois.edu
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-cors-header@kubernetescrd
  ingress:
    tls: true
    hostname: minio.mmli.fastapi.mmli1.ncsa.illinois.edu
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-cors-header@kubernetescrd
  global:
    storageClass: csi-cinder-sc-retain
  auth:
    existingSecret: "mmli-backend-minio"

extraDeploy:
# Enable DecentCI backups
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mmli-backend-backups
    namespace: alphasynthesis
    labels:  
      app.kubernetes.io/name: decentci-backups
      app.kubernetes.io/component: config
  data:
    backups: |
      # TODO: Configure backups for MinIO?
      #- backup-name: decentci-backups-mmli-backend-minio-files

      - backup-name: decentci-backups-mmli-backend-db
        schedule: "01 7 * * *"
        database:
          type: postgresql
          host: mmli-backend-postgresql.alphasynthesis.svc.cluster.local
          auth:
            username: mmli
            database: mmli
            passwordKey: postgres-password
            existingSecret: mmli-backend-postgresql
    global: |
      enabled: true
      backup-nfs-path: /taiga/ncsa/radiant/bbfp/mmli1/backups/mmli-backend
      backup-nfs-server: taiga-nfs.ncsa.illinois.edu

- apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    creationTimestamp: null
    name: mmli-backend-postgresql
    namespace: alphasynthesis
  spec:
    encryptedData:
      password: AgAcDpEFjkpr4dSrQGjJtlL1W3z76pljqDsCrsNDzLhQRAjQJQeql9vG5zazAWSFRxxhO4jH8XATa0R7Nr+bHaBH3RsheposrMXUSazHsIVNkYqAnURZ/ZEIKU6lxxp/KdaeNyJ0ta1KOzUGq18pjFYMHTPVcBwRq0kqNn4fugJSlNWdPoqr1y9Dk8khXCHgj4f8D7+ypy5q5D4drYEwa2ASxeZPRixOlu9v1RHQPTncAiEpC+6o+Z0mjUPNdT2Ty63H2BFSqVxB355SJkSVbufmjEXhP/G6eE99ls1zA2fQce7mqTckmylXXE7a9BWM99dfyk/bCtKVtjD1HlD5jsUJ2GIjr8JUnJ6Uoodu2RF6uOQ5fJTXA51Ccqd69iqtHGgwk834da3TvnM7yZNoo5I1RH4SGqN/p+wj2lpPfjJ1OMbhTO4odQS21bgbxbBjj2BwGPAsEteywD3wiI8XUlWOObCJrZXLaxH0nca6UuFfvUL57IT+YModgHS6XAXf7C/KMc44KPWvG2e5ksKT1kzuicMjulQD4aBRKcYYmOvPv0NzzTSC2zisaOb+jeYg7hKvRkKRAZlXxNtrt0FF5S6u0oKS0odpBxb03LD6bnQ3NB3zvjODJGobkudlcJSlrDG4unubeDq2c5VJ60vt0O/shm39m6Lr8ECSR8aV2FmOrUgXcKQ/9l4kzN6IeihZe/477M6pho0X0A5zc0cHm2pS0xF87Ny1jA8BbS4vZENODA==
      postgres-password: AgCuvYzQpG6cQZx7jxd+7f2/lhx/73Hf2j/Yi2JK267AOcteQdrIPESCgBoRjXnaQ3jj5MjgQLC09VtBPlVvXq/6RIomvhHvlE2PlI4QkqwgS4nCmWZp+IAQNb3DdG3L2B3PIf28u4sXW73eZYHnqPBzPtmwWDi1B542eRViuDY5nK1Ziu1IN03ZUVOJPVoe7XJLcevw7EGAZ5/aGXDQF5XlBK4Dliwr9WlWLxiMYRvo9wbcYHF0Ll6vC1I/U6rDR42ZcWK92Mkg3XZin5qxdCbyOxUuBbi5+9dFh4ovB7e+5oPJVNGpWGs017iEl+3ZrtJQD2nRS0GYWFlnl3u2R4O2yDpxlCJ10kc84IFRFHF17p9ZkWPY1E4T5fFlR/ctvBFCp3BhKB70zqzQdmiY6cywbTtf4IXuPbsqQ70m7RfRLTc7D4Qu0zbPbM7QPN+aDpJW+MK8Xp11ajhfcfflw5FkR5DYX6knH52Tl81E0YjAL5pCCMKZz8GbkNMHSgPn7VVoMJavG1qYG3pmEFLMs5CA0AWOKD/VaNWCJKCUe8v+h5DMcsHpAFYEkPIffYzKcWNNC8wdW1AWYftY54EfkSMpNdbB56ZVU8ORm02NtJ9paQiI0BgzSqMKIDL5DdA4EEbi+HXV8ePd0cA00bwo/y8epYcQ5nGfW8WUHxmI18mbFVaxs06ZKIy8mu49JF/c+UpJ38rSXlghKPiHLha2oR0BSAJmVH4LbFRb43TljMEIZg==
    template:
      metadata:
        creationTimestamp: null
        name: mmli-backend-postgresql
        namespace: alphasynthesis
  

  
- apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    creationTimestamp: null
    name: mmli-backend-minio
    namespace: alphasynthesis
  spec:
    encryptedData:
      root-password: AgCG/7VjxMAxYQ1bgMPv5dokXPenhx7rfkN1I7j75wmsaMXj3FHRXCI7Q+l0aAhGK/KwIZhB2fmzQiY3WXuyFpXXf3TemD3lBJHZ4HaOBL1CbppvUykcygdxls8f3gVaRMOflvVMDlcMApAbbjK7bfuwzAfTgSa6e/o67uJZBxx/EqSiIhFw448M5PudKZGvdGjGgpD9awsHu4ZZHM/bGDKtfDFj4BYYq8pNfeS3//dBsZE97dHQ0kFWUYLszkFH2VEaNcH29H4oRIZXBBvIKELVcg0NnaQW6NgbiclC33M0Uw57KEICLJ3mhPyNlY2XNBcRYMImlaWxkc8XoDsXRtaaYJaXkm/9ujdbF3vkbMUjNhAIWArxZJEOXt7m+S+1tV0MpwfxIk8o+0U1R0SxGDKknW6ywqhTUjjT1DqhUSsPmghHEPxVABEJPF8ISV1igjO/tZdqeKoAc6vY+JGlo5vM+JtewyzE62953iAio0GOVoezvmQP267AU2RwmfFM+6zHvI2C6NdEsmZ/ZJW0l0gZoF7cPrg7ggpmzbNjQ3ZU6UGoVZjaaR5kU53zcX7vHIc/YIR+RDUCzaSHoZMuRewcTKY0mzXOJcArNxb8fklF2sqIiwZWi2MAbPShkfmcQQSV3gwmR9FQJHG+VoAbt1WPpVYHlRwA4I+L0w9h957NKjHILIh1Wn9UhL8NzCbrjrlLzYlbzYdK6un8ai+JhTD3tYSLK6uNiseP/fBsSYKY7g==
      root-user: AgDBju+PkUEBDL57qFzqzWWFOF2q+iSRxDdEMGDraStRSNETsa3C4vhaDvyZIR2zR5mskzKp+1OtGogaB9vNVLKIfdOxJggrAlUOgHE6A53QuBUAigYsX3zxEqipetDiKV7xqXCnoljzzSpd8O/my/vFcTkvCcHBou9OLo8snzjs8DKmvmiJuheMtWXYoZEkxsJYH0m4yow4ovrUl5X++TfKmuzugTV0i/hDQ6lULs6W4sELwYoviB3Y3VdOyW/Lem/dCCgKAi2Q8eLjqdDeLgjN+ryIH3pNkBo78A3VOXi1JQEfjWXwyfQY2Q9PRZwl1yvFveP3dogKWL9TLhYkIDsDskMe2vZtsQEunisHALFgpMRRh11TLRUvX4bDobrWzBm+wfd961xFf2zLJ2nNdBKCFxtF6RS5fp9coLOul2n3FRIGnhU4ogn+zjkaB2yRllBhxhc9xWSsQw96fcCicOxp35IklsTpEDjhsAcVvUxoOPu26kZfatDFRkUCoLasxAfn2xOLuxPIbWZqbCXOm41bvRl4KA5ri+rgj1AjHHaUlK0v+JFoRp0Z0pStwD5fKaxXX1ts5jTMPSGVuPNlV+4Lmvl82EAGTsr2eytG9Zus89NW4vkdf7Yen2l+a3NtuJ9RqZwUm0Ev4zwll5H7d8i/Gy4P1ZidEshfpR9APxpP4hTny8l0I6te3bFklbqcgpY/3zlpjTIu//nsAybTIjB5aH+d5QGRbuVEfGVgNSVYHQ==
    template:
      metadata:
        creationTimestamp: null
        name: mmli-backend-minio
        namespace: alphasynthesis
