ingress:
  ingressClassName: nginx

config:
  external:
    chemscraper:
      # Change to local chemscraper service URL if deployed in local cluster
      apiBaseUrl: "https://chemscraper.backend.staging.mmli1.ncsa.illinois.edu"
      frontendBaseUrl: "http://localhost:4200"

controller:
  image: moleculemaker/mmli-backend:kubejob

postgresql:
  enabled: true
#  global:
#    storageClass: hostpath
  auth:
    password: "postgres"
    postgresPassword: "postgres"
    username: "postgres"
    database: "mmli"

minio:
  enabled: true
  apiIngress:
    ingressClassName: nginx
  ingress:
    ingressClassName: nginx
#  global:
#    storageClass: hostpath
  auth:
    rootUser: minioadmin
    rootPassword: minioadmin
