ingress:
  ingressClassName: nginx

config:
# Change to local chemscraper service URL if deployed in local cluster
  chemscraper_url: "https://chemscraper.backend.staging.mmli1.ncsa.illinois.edu"
  chemscraper_frontend_url: "http://localhost:4200"

postgresql:
  enabled: true
#  global:
#    storageClass: hostpath
  auth:
    rootPassword: "postgres"
    password: "postgres"
    username: "postgres"
    database: "mmli"

minio:
  enabled: true
  apiIngress:
    ingressClassName: nginx
  ingress:
    ingressClassName: nginx
#  global:
#    storageClass: hostpath
  auth:
    rootUser: minioadmin
    rootPassword: minioadmin
