version: "3.8"
services:
  postgresql:
    container_name: mmli-backend-postgresql
    image: postgres:15
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"
  minio:
    container_name: mmli-backend-minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - "minio:/data"
    command: server --console-address ":9001" /data
  rest:
    container_name: mmli-backend
    image: moleculemaker/mmli-backend:kubejob
    restart: on-failure
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    depends_on:
      - postgresql
      - minio
    build: 
      context: .
    ports: 
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./migrations:/code/migrations
      - /Users/lambert8/.kube/config:/opt/kubeconfig

volumes:
  postgres:
  minio:
