version: "3.8"
services:
  postgresql:
    container_name: mmli-backend-postgresql
    image: postgres:15
    networks:
      - mmli-net
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./seeds:/data/seeds"
  minio:
    container_name: mmli-backend-minio
    image: minio/minio
    networks:
      - mmli-net
    ports:
      - "9001:9001"
      - "9002:9002"
    env_file:
      - .env
    volumes:
      - "minio:/data"
    command: server --console-address ":9001" /data
  rest:
    container_name: mmli-backend
    image: moleculemaker/mmli-backend:kubejob
    restart: on-failure
    networks:
      - mmli-net
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--reload"
      ]
    depends_on:
      - postgresql
      - minio
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./migrations:/code/migrations
      - $HOME/.kube/config:/opt/kubeconfig
      - $HOME/.minikube/ca.crt:$HOME/.minikube/ca.crt
      - $HOME/.minikube/profiles/minikube/client.crt:$HOME/.minikube/profiles/minikube/client.crt
      - $HOME/.minikube/profiles/minikube/client.key:$HOME/.minikube/profiles/minikube/client.key

networks:
  mmli-net:
    external: true
    name: mmli-net

volumes:
  postgres:
  minio:
