# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: mmli-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmli-fastapi
  template:
    metadata:
      labels:
        app: mmli-fastapi
    spec:
      containers:
        - name: mmli-fastapi
          image: {{ .Values.controller.image }}
          env:

          - name: POSTGRES_HOST
{{- if .Values.postgresql.hostname }}
            value: {{ .Values.postgresql.hostname }}
{{ else }}
            value: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}

          - name: POSTGRES_PASSWORD
{{- if .Values.postgresql.auth.existingSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.auth.existingSecret }}
                key: postgres-password
{{- else }}
            value: {{ .Values.postgresql.auth.password }}
{{- end }}

          - name: POSTGRES_DATABASE
            value: {{ .Values.postgresql.auth.database }}

          - name: POSTGRES_USER
            value: {{ .Values.postgresql.auth.username }}

          - name: DATABASE_URL
            value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DATABASE)"

          ports:
            - containerPort: 8080
          imagePullPolicy: Always
