"""add reaction/enzymes table

Revision ID: 0662ce209143
Revises: 30b240622d34
Create Date: 2024-07-27 17:40:33.431799

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0662ce209143'
down_revision = '30b240622d34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enziid_enzseq',
    sa.Column('seq', sa.Text(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions_enzids',
    sa.Column('reaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enz_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('reaction_id', 'enz_id')
    )
    op.create_table('enzids_enziids',
    sa.Column('enz_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enz_iid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['enz_iid'], ['enziid_enzseq.id'], ),
    sa.PrimaryKeyConstraint('enz_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enzids_enziids')
    op.drop_table('reactions_enzids')
    op.drop_table('enziid_enzseq')
    # ### end Alembic commands ###
