"""add chemical identifier model and table

Revision ID: 30b240622d34
Revises: e8569ab45dd1
Create Date: 2024-04-18 10:13:36.010916

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '30b240622d34'
down_revision = 'e8569ab45dd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metanetx_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inchi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inchi_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('smiles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kegg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formula', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_identifier_kegg_id'), 'chemical_identifier', ['kegg_id'], unique=False)
    op.create_index(op.f('ix_chemical_identifier_metanetx_id'), 'chemical_identifier', ['metanetx_id'], unique=False)
    op.create_index(op.f('ix_chemical_identifier_name'), 'chemical_identifier', ['name'], unique=False)
    op.create_index(op.f('ix_chemical_identifier_smiles'), 'chemical_identifier', ['smiles'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chemical_identifier_smiles'), table_name='chemical_identifier')
    op.drop_index(op.f('ix_chemical_identifier_name'), table_name='chemical_identifier')
    op.drop_index(op.f('ix_chemical_identifier_metanetx_id'), table_name='chemical_identifier')
    op.drop_index(op.f('ix_chemical_identifier_kegg_id'), table_name='chemical_identifier')
    op.drop_table('chemical_identifier')
    # ### end Alembic commands ###
