"""add chemical_identifier table

Revision ID: 7ae725ff52b6
Revises: e8569ab45dd1
Create Date: 2024-04-17 03:31:23.419572

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7ae725ff52b6'
down_revision = 'e8569ab45dd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metanetx_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, index=True),
    sa.Column('inchi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inchi_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True, index=True),
    sa.Column('smiles', sqlmodel.sql.sqltypes.AutoString(), nullable=True, index=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kegg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, index=True),
    sa.Column('formula', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical_identifier')
    # ### end Alembic commands ###
