"""removed moleculecacheentry

Revision ID: e8569ab45dd1
Revises: 88355d0f323b
Create Date: 2023-12-18 05:40:22.401139

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e8569ab45dd1'
down_revision = '88355d0f323b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flaggedmolecule_smile_fkey', 'flaggedmolecule', type_='foreignkey')
    op.drop_table('moleculecacheentry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moleculecacheentry',
    sa.Column('smile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pub_chem_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('molecular_formula', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('molecular_weight', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chemical_safety', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('smile', name='moleculecacheentry_pkey')
    )
    op.create_foreign_key('flaggedmolecule_smile_fkey', 'flaggedmolecule', 'moleculecacheentry', ['smile'], ['smile'])
    # ### end Alembic commands ###
