"""init

Revision ID: fd23b24f6f9a
Revises: 
Create Date: 2023-07-20 00:09:12.430427

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fd23b24f6f9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job', 'job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
