"""Valid `--blast_org` reference organisms for CRISPR-COPIES.

Snapshot of the distinct `Organism` values in the method's bundled
`essential_genes/deg.csv` (the Database of Essential Genes). main.py matches
`--blast_org` against these names with an EXACT `.isin(...)` test, so the
frontend dropdown and this list must stay byte-for-byte identical to deg.csv.

REGENERATE this list whenever deg.csv changes.
"""

DEG_ORGANISMS: frozenset[str] = frozenset({
    "Acinetobacter baumannii ATCC 17978",
    "Acinetobacter baylyi ADP1",
    "Agrobacterium fabrum str. C58",
    "Arabidopsis thaliana",
    "Aspergillus fumigatus",
    "Bacillus subtilis 168",
    "Bacillus thuringiensis BMB171",
    "Bacteroides fragilis 638R",
    "Bacteroides thetaiotaomicron VPI-5482",
    "Bombyx mori",
    "Brevundimonas subvibrioides ATCC 15264",
    "Burkholderia cenocepacia J2315 chromosome 1",
    "Burkholderia cenocepacia strain K56-2 scf7180000000048",
    "Burkholderia pseudomallei K96243",
    "Burkholderia thailandensis E264",
    "Caenorhabditis elegans",
    "Campylobacter jejuni subsp. jejuni 81-176",
    "Campylobacter jejuni subsp. jejuni NCTC 11168 = ATCC 700819",
    "Caulobacter crescentus",
    "Danio rerio",
    "Drosophila melanogaster",
    "Escherichia coli MG1655 I",
    "Escherichia coli MG1655 II",
    "Escherichia coli O157:H7 str. EDL933",
    "Escherichia coli ST131 strain EC958",
    "Francisella novicida U112",
    "Francisella tularensis subsp. tularensis SCHU S4 complete gen",
    "Haemophilus influenzae Rd KW20",
    "Helicobacter pylori 26695",
    "Homo sapiens",
    "Komagataella phaffii GS115 chromosome 1",
    "Methanococcus maripaludis S2",
    "Mus musculus",
    "Mycobacterium avium subsp. hominissuis strain MAC109",
    "Mycobacterium tuberculosis H37Rv",
    "Mycobacterium tuberculosis H37Rv II",
    "Mycobacterium tuberculosis H37Rv III",
    "Mycoplasma genitalium G37",
    "Mycoplasma pneumoniae M129",
    "Mycoplasma pulmonis UAB CTIP",
    "Neisseria gonorrhoeae MS11",
    "Plasmodium falciparum",
    "Porphyromonas gingivalis ATCC 33277",
    "Providencia stuartii strain BE2467",
    "Pseudomonas aeruginosa PAO1",
    "Pseudomonas aeruginosa UCBPP-PA14",
    "Ralstonia solanacearum GMI1000",
    "Rhodopseudomonas palustris CGA009",
    "Saccharomyces cerevisiae",
    "Salmonella enterica serovar Typhi",
    "Salmonella enterica serovar Typhi Ty2",
    "Salmonella enterica serovar Typhimurium SL1344",
    "Salmonella enterica subsp. enterica serovar Typhimurium str. 14028S",
    "Salmonella typhimurium LT2",
    "Schizosaccharomyces pombe 972h-",
    "Shewanella oneidensis MR-1",
    "Sphingomonas wittichii RW1",
    "Staphylococcus aureus N315",
    "Staphylococcus aureus NCTC 8325",
    "Staphylococcus aureus subsp. aureus MRSA252",
    "Staphylococcus aureus subsp. aureus MSSA476",
    "Staphylococcus aureus subsp. aureus MW2",
    "Staphylococcus aureus subsp. aureus NCTC 8325",
    "Staphylococcus aureus subsp. aureus USA300_TCH1516",
    "Streptococcus agalactiae A909",
    "Streptococcus mutans UA159",
    "Streptococcus pneumoniae",
    "Streptococcus pyogenes MGAS5448",
    "Streptococcus pyogenes NZ131",
    "Streptococcus sanguinis",
    "Streptococcus suis P1/7 complete gen",
    "Sulfolobus islandicus M.16.4",
    "Synechococcus elongatus PCC 7942",
    "Vibrio cholerae N16961",
    "Vibrio cholerae O1 biovar El Tor str. N16961 chromosome I",
})
